import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  fr: {
    translation: {
      // Navigation
      dashboard: "Dashboard",
      previsions: "Prévisions",
      carteLogistique: "Carte logistique",
      rapportIA: "Rapport IA",
      profil: "Profil",
      parametres: "Paramètres",
      connexion: "Connexion",
      deconnexion: "Déconnexion",
      
      // Dashboard
      dashboardTitle: "Dashboard LogiMind",
      dashboardSubtitle: "Vue d'ensemble de vos performances logistiques en temps réel",
      commandesEnCours: "Commandes en cours",
      tauxRupture: "Taux de rupture",
      coutLogistique: "Coût logistique moyen",
      evolutionDemande: "Évolution de la demande",
      alertesRecentes: "Alertes récentes",
      resumePerformances: "Résumé des performances",
      tauxLivraison: "Taux de livraison",
      delaiMoyen: "Délai moyen",
      caMensuel: "CA mensuel",
      entrepotsActifs: "Entrepôts actifs",
      
      // Prévisions
      previsionsTitle: "Prévisions de demande",
      previsionsSubtitle: "Analysez et prédisez la demande future grâce à l'intelligence artificielle",
      parametresPrevision: "Paramètres de prévision",
      produit: "Produit",
      entrepot: "Entrepôt",
      periode: "Période",
      lancerPrevision: "Lancer la prévision",
      generation: "Génération...",
      
      // Carte
      carteTitle: "Carte logistique",
      carteSubtitle: "Visualisez vos flux logistiques et l'état de vos entrepôts en temps réel",
      
      // Rapport IA
      rapportTitle: "Rapport IA",
      rapportSubtitle: "Rapport mensuel automatisé généré par l'intelligence artificielle",
      
      // Profil
      profilTitle: "Profil utilisateur",
      profilSubtitle: "Gérez vos informations personnelles et préférences",
      
      // Paramètres
      parametresTitle: "Paramètres",
      parametresSubtitle: "Configurez vos préférences et paramètres d'application",
      notifications: "Notifications",
      apparence: "Apparence",
      securite: "Sécurité et confidentialité",
      preferencesMetier: "Préférences métier",
      theme: "Thème",
      langue: "Langue",
      formatDate: "Format de date",
      sauvegarder: "Sauvegarder",
      reinitialiser: "Réinitialiser",
      
      // Commun
      normal: "Normal",
      retard: "Retard",
      rupture: "Rupture",
      haute: "Haute",
      moyenne: "Moyenne",
      faible: "Faible",
      semaine: "Semaine",
      mois: "Mois",
      unites: "unités"
    }
  },
  en: {
    translation: {
      // Navigation
      dashboard: "Dashboard",
      previsions: "Forecasts",
      carteLogistique: "Logistics Map",
      rapportIA: "AI Report",
      profil: "Profile",
      parametres: "Settings",
      connexion: "Login",
      deconnexion: "Logout",
      
      // Dashboard
      dashboardTitle: "LogiMind Dashboard",
      dashboardSubtitle: "Real-time overview of your logistics performance",
      commandesEnCours: "Orders in progress",
      tauxRupture: "Stockout rate",
      coutLogistique: "Average logistics cost",
      evolutionDemande: "Demand evolution",
      alertesRecentes: "Recent alerts",
      resumePerformances: "Performance summary",
      tauxLivraison: "Delivery rate",
      delaiMoyen: "Average delay",
      caMensuel: "Monthly revenue",
      entrepotsActifs: "Active warehouses",
      
      // Prévisions
      previsionsTitle: "Demand forecasting",
      previsionsSubtitle: "Analyze and predict future demand with artificial intelligence",
      parametresPrevision: "Forecast parameters",
      produit: "Product",
      entrepot: "Warehouse",
      periode: "Period",
      lancerPrevision: "Launch forecast",
      generation: "Generating...",
      
      // Carte
      carteTitle: "Logistics map",
      carteSubtitle: "Visualize your logistics flows and warehouse status in real time",
      
      // Rapport IA
      rapportTitle: "AI Report",
      rapportSubtitle: "Automated monthly report generated by artificial intelligence",
      
      // Profil
      profilTitle: "User profile",
      profilSubtitle: "Manage your personal information and preferences",
      
      // Paramètres
      parametresTitle: "Settings",
      parametresSubtitle: "Configure your preferences and application settings",
      notifications: "Notifications",
      apparence: "Appearance",
      securite: "Security and privacy",
      preferencesMetier: "Business preferences",
      theme: "Theme",
      langue: "Language",
      formatDate: "Date format",
      sauvegarder: "Save",
      reinitialiser: "Reset",
      
      // Commun
      normal: "Normal",
      retard: "Delay",
      rupture: "Stockout",
      haute: "High",
      moyenne: "Medium",
      faible: "Low",
      semaine: "Week",
      mois: "Month",
      unites: "units"
    }
  },
  es: {
    translation: {
      // Navigation
      dashboard: "Panel",
      previsions: "Previsiones",
      carteLogistique: "Mapa Logístico",
      rapportIA: "Informe IA",
      profil: "Perfil",
      parametres: "Configuración",
      connexion: "Iniciar sesión",
      deconnexion: "Cerrar sesión",
      
      // Dashboard
      dashboardTitle: "Panel LogiMind",
      dashboardSubtitle: "Visión general en tiempo real de su rendimiento logístico",
      commandesEnCours: "Pedidos en curso",
      tauxRupture: "Tasa de ruptura",
      coutLogistique: "Costo logístico promedio",
      evolutionDemande: "Evolución de la demanda",
      alertesRecentes: "Alertas recientes",
      resumePerformances: "Resumen de rendimiento",
      tauxLivraison: "Tasa de entrega",
      delaiMoyen: "Retraso promedio",
      caMensuel: "Ingresos mensuales",
      entrepotsActifs: "Almacenes activos",
      
      // Commun
      normal: "Normal",
      retard: "Retraso",
      rupture: "Ruptura",
      haute: "Alta",
      moyenne: "Media",
      faible: "Baja",
      semaine: "Semana",
      mois: "Mes",
      unites: "unidades"
    }
  },
  de: {
    translation: {
      // Navigation
      dashboard: "Dashboard",
      previsions: "Prognosen",
      carteLogistique: "Logistikkarte",
      rapportIA: "KI-Bericht",
      profil: "Profil",
      parametres: "Einstellungen",
      connexion: "Anmelden",
      deconnexion: "Abmelden",
      
      // Dashboard
      dashboardTitle: "LogiMind Dashboard",
      dashboardSubtitle: "Echtzeit-Übersicht Ihrer Logistikleistung",
      commandesEnCours: "Laufende Bestellungen",
      tauxRupture: "Ausfallrate",
      coutLogistique: "Durchschnittliche Logistikkosten",
      evolutionDemande: "Nachfrageentwicklung",
      alertesRecentes: "Aktuelle Warnungen",
      resumePerformances: "Leistungszusammenfassung",
      tauxLivraison: "Lieferrate",
      delaiMoyen: "Durchschnittliche Verzögerung",
      caMensuel: "Monatsumsatz",
      entrepotsActifs: "Aktive Lager",
      
      // Commun
      normal: "Normal",
      retard: "Verzögerung",
      rupture: "Ausfall",
      haute: "Hoch",
      moyenne: "Mittel",
      faible: "Niedrig",
      semaine: "Woche",
      mois: "Monat",
      unites: "Einheiten"
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'fr',
    debug: false,
    interpolation: {
      escapeValue: false,
    },
    detection: {
      order: ['localStorage', 'navigator'],
      caches: ['localStorage']
    }
  });

export default i18n;